### PR TITLE
Contribute tutorial

### PR DESCRIPTION
**Pull request by hotpheex**
Added writeup on how to contribute to KB

### CODE REVIEW

**Comment by 0ketz** [comment]
Generally speaking I won't approve PR's that are outside of the `content/` directory.
This is a bit different though. 

Would it be possible to move the content of ` content/_articles/contributing.md` and place it into `_pages/contributing.md`, whilst preserving the front matter that is in `_pages/contributing.md` (but please also write a note in the content that says that you wrote this). 

Thanks 😘

**Review by 0ketz — CHANGES_REQUESTED** [review]
Please move the content of content/_articles/contributing.md and place it into _pages/contributing.md, whilst preserving the front matter that is in _pages/contributing.md (but please also write a note in the content that says that you wrote this).

**Comment by hotpheex** [comment]
Aah sorry dude didn't even notice the "contributing" page there haha.
I'll fix it up and push it up in a tick

**Comment by hotpheex** [comment]
Request fixed & pushed up. Should be good to go

**Review by 0ketz — APPROVED** [review]
Looks great!

**Pull request merged**
